@startuml comps

title Components diagram

actor User

skinparam component {
    backgroundColor<<black box>> #414559
    fontColor<<black box>> #fff
}

package "Orders System" {
    () "HTTP Api" as orderApi
    [Order Component] as order
    database Orders as orderDb
}
() "HTTP Api" as storeApi

[Product Store Component]<<black box>> as store

User -> orderApi

orderApi - order
storeApi - store

order ..> storeApi
order -> orderDb

@enduml